import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Skillsbox from '@/components/skills'
import styled from 'styled-components'
import Projectbox from '@/components/projects'
import Seemore from '@/components/button'
import Contactsbox from '@/components/contacts'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      
<div className={styles.colorrow}>
    <div className={styles.headercontentcolumn}>
      
    <h1 className={styles.headerfont}>Tyler Lee</h1>
    <div className={styles.row}>
    <h1 className={styles.headerstatic}>I can be your   </h1>
      <ul className={styles.list}>
      <li><span> Graphic Designer</span></li>
      </ul>
      </div>
    <p className={styles.contentfont}>
    Hi there, I'm a Digital, Design, and Development student who specializes in graphic design. 
    My main areas of expertise are in Photoshop, Illustrator, Indesign, and utilizing Autodesk sketchbook. 
    I have experience in working with teams to create visually appealing products that have been user tested towards a specific market.
    </p>
    </div>

    <div className={styles.piccolumn}>
    <Image
    src="/thumbnail wordpress v2.png"
    width={1100}
    height={650}
    
    />



    </div>


</div>


<div className={styles.purpleheader}>Projects</div>
    <div className={styles.row}>
      <div className={styles.leftycolumn}>
        <div className={styles.grow}>
    <Projectbox src="yugioh demo.png"
    heading="Role: Graphic desginer "
    text='This was a solo project where I created digital illustrations of two 
    yu-gi-oh characters. I used autodesk sketchbook to create them and a majority of the graphical assets, like the card backs.'
    date="November 2022 to December 2022"

    bg="#FFFFFF"
    />
    </div>
    <div className={styles.grow}>
    <Projectbox src="Tactical Pigeons.png"
    heading="Role: Graphic desginer "
    text='Tactical pigeons is a rock paper scissors based game with pigeons competing for food as the main attraction. On this game I developed the graphics for the pigeons in illustrator and colored them all there as well.'
    date="January 2022 to April 2022"

    bg="#FFFFFF"
    />
    </div>
  </div>
<div className={styles.rightycolumn}>
<div className={styles.grow}>
<Projectbox src="trackstacks.png"
    heading="Role: UI/UX designer  "
    text='An expo app that aims to assist those with ADHD properly stay on task and help them time manage. In this project I performed user research and testing. I worked along side 3 other designers to create page layouts and structures for the app.'
    date="September 2022 to December 2022"
    
    bg="#FFFFFF"
    />
    </div>
    <div className={styles.grow}>
    <Projectbox src="Elevate.png"
    heading="Role: UI/UX designer "
    text='Elevate is a Figma mockup of a music streaming app, simalair to apple music and spottily. I developed the layout of the main page, sign in page and purchasing pages. I referenced the previously mentioned apps to give a familiar and effective design..'
    date="January 2022 to April 2022"
    
    bg="#FFFFFF"
    />
    </div>
</div>

    </div>
      <div className={styles.purpleheader}>Graphics</div>
      
      <hr/>
        <div className={styles.rowpics}>
        <div className={styles.spacing}>
        <div className={styles.conty}> 
          <Image
          src="/Discovering china.png"
          width={550}
          height={500}
          
          />
         
         <div className={styles.overlay}>

<div className={styles.contenty}>
<h2>Indesign mulitpage magazine</h2>
<p>An 8 page magazine featuring various photos of Chinese architecture.  I used Indesign to crwate the layout and the character and paragraph styles.</p>

</div>
</div>
</div>
          </div>
          
          <div className={styles.spacing3}>
          <div className={styles.conty}>
                          <Image
                src="/Noctis edit.png"
                width={400}
                height={500}
               
                />
              <div className={styles.overlay}>

                  <div className={styles.contenty}>
                    <h2>Noctis Character Edit</h2>
                  <p>Graphical edit of a Noctis cosplayer. I used photoshop and Illustrator to create this graphic. 
                    I masked out the cosplayer from the proginal background, masked a sword figurine and added to the graphic, created a custom crystal brush and added afterglow to illuminate the night background.</p>

                  </div>
          </div>

          </div>
          
          </div>          
          <div className={styles.spacing2}>
            <div className={styles.conty}>
                    <Image
          src="/End of us photoshop.jpg"
          width={550}
          height={500}
       
          />
              <div className={styles.overlay}>

          <div className={styles.contenty}>
          <h2>Album Cover</h2>
          <p>Pure photoshop project where I created my own custom space background using various filters and colored brushes. 
            The black hole was created by my self as well and the meteors contain blur effects.</p>

          </div>
          </div>


          </div>
          </div>  
        </div>
        <div className={styles.rowb}>
        
        <Seemore
            
        />

    </div>
        <div className={styles.purpleheader}>Skills</div>
        <div className={styles.row}>
        <div class={styles.maincontainer}>

          <div class={styles.thecard}>


            <div class={styles.thefront}>

              <Image
              src="/Photoshop.png" 
              width={90}
              height={80}
              />
              <h1>Photoshop</h1>
              <p className={styles.typography}>I am the most experienced in this application and I can comfortable, masking images, color changing, creating posters and editing faces.</p></div>

            <div class={styles.theback}> 
            <Image
            src="/Noctis edit.png"
            width={550}
            height={500}
            />
           </div>

          </div>
          </div>

          <div class={styles.maincontainer2}>
          <div class={styles.thecard2}>


            <div class={styles.thefront2}>

              <Image
              src="/Illustrator.png" 
              width={90}
              height={80}
              />
              <h1>Illustrator</h1>
              <p className={styles.typography}>I have experience creating icons, vectors, logos and character Illustrations with the application.</p></div>

            <div class={styles.theback2}> 
            <Image
            src="/Bellatrix Blueberry.png"
            width={400}
            height={500}
            />
           </div>

          </div>
          </div>
          <div class={styles.maincontainer3}>
          <div class={styles.thecard3}>


            <div class={styles.thefront3}>

              <Image
              src="/Indesign.png" 
              width={90}
              height={80}
              />
              <h1>Indesign</h1>
              <p className={styles.typography}>In InDesign I've created various layouts, poster designs and an interactive project combining both the other programs to create visual assets.</p></div>

            <div class={styles.theback3}> 
            <Image
            src="/yugioh screen.png"
            width={550}
            height={500}
            />
           </div>

          </div>
          </div>
          </div>

        <div className={styles.purpleheader}>Contact</div>
      <space></space>
      <hr/>
        <div className={styles.row}>
          <div className={styles.contactspace}>
        <Contactsbox src="/Gmail.png" 
        heading="Email"
        text='You can reach me at either 
        tylerlee1295@gmail.com or
        tylerlee888@hotmail.com' 
        me="80px" 
        bg="linear-gradient(#6EA2D1, #F2295B)"
        
        />
        <Contactsbox src="/Linkedin.png" 
        heading="Social media"
        text="I'm not the most active on Linkedin but I will respond within a day, click here to visit my page." 
        me="90px" 
        bg="linear-gradient(#B848F0, #29A3F2)"
        
        />
        <Contactsbox src="/phone.png" 
        heading="Phone"
        text="I will reply to your text within a day at
        778-558-1388." 
        me="-10px" 
        bg="linear-gradient(#E187DE, #F2295B)"
        
        />
 </div>
        </div>

          
      </main>
    </>
  )
}


const space = styled.div `
height: 200px
`
